#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.


menuentry 'Debian install' {
    set background_color=black
	set root=${myroot}
    linux /debian/vmlinuz vga=788 --- quiet 
    initrd /debian/initrd.gz
}

menuentry 'CentOS install' {
    set background_color=black
	set root=${myroot}
    set isofile="/centos/CentOS-7-x86_64-Minimal-1804.iso"
	loopback loop ${isofile}
	linux (loop)/isolinux/vmlinuz inst.stage2=hd:UUID=${myuuid}:/${isofile} rhgb
	initrd (loop)/isolinux/initrd.img 
}


menuentry 'ArchLinux install'{
    set background_color=black
	set root=${myroot}
    set isofile="/archlinux/archlinux-2018.09.01-x86_64.iso"
	loopback loop ${isofile}
    linux (loop)/arch/boot/x86_64/vmlinuz img_label=GRUB2 img_loop=${isofile}  systemd.wants=sshd.service
    initrd (loop)/arch/boot/x86_64/archiso.img
}


menuentry 'CentOS 7' {
    set background_color=black
	set root=${myroot}
	configfile /boot/grub2/grub.cfg
}
