#!/bin/sh
cat <<EOF
if [ -f  \${config_directory}/custom.cfg ]; then
  source \${config_directory}/custom.cfg
elif [ -z "\${config_directory}" -a -f  \$prefix/custom.cfg ]; then
  source \$prefix/custom.cfg;
fi
EOF

myroot='hd2,msdos1'
mydev=/dev/sdc1
cat<<EOF
myroot=${myroot}
mydev=${mydev}
myuuid=`blkid ${mydev} -s UUID | awk -F '"' '{print $2}'`
EOF
#set myuuid=`blkid /dev/sdc1 -s UUID | awk -F '"' '{print $2}'`
#set myuuid=`blkid /dev/sdc1 -s UUID|sed "s#.*=##g"`
#set myuuid=`ls /dev/disk/by-uuid/ -al|grep sdc1$|awk '{print $9}'`
